name: terraform-destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm full destroy of infra (workspace: prod)"
        required: true
        default: "NO"

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  GOOGLE_PROJECT: <your_project_id>
  GOOGLE_REGION: europe-west1

jobs:
  destroy:
    # Safety guard â€“ only run when user explicitly types DESTROY
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      # Same auth pattern as apply
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - uses: hashicorp/setup-terraform@v3
      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Select/Create Workspace (prod)
        run: |
          terraform -chdir=infra workspace select prod \
          || terraform -chdir=infra workspace new prod

      - name: Terraform Destroy (prod)
        run: terraform -chdir=infra destroy -auto-approve -input=false -var "project_id=${{ env.GOOGLE_PROJECT }}" -var "region=${{ env.GOOGLE_REGION }}"
