# .github/workflows/terraform-plan.yml
name: terraform-plan

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform-*.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test, prod]   
    env:
      TF_IN_AUTOMATION: "true"
      TF_ENV: ${{ matrix.env }}          # dev / test / prod
      GOOGLE_PROJECT: {project id}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Select/Create Workspace (${{ env.TF_ENV }})
        run: |
          terraform -chdir=infra workspace select "${{ env.TF_ENV }}" \
          || terraform -chdir=infra workspace new "${{ env.TF_ENV }}"

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Terraform Plan (${{ env.TF_ENV }})
        run: |
          terraform -chdir=infra plan \
            -no-color \
            -input=false \
            -var-file="${{ env.TF_ENV }}.tfvars" \
            -out="tfplan-${{ env.TF_ENV }}"

      - name: Show Plan (${{ env.TF_ENV }})
        run: terraform -chdir=infra show -no-color "tfplan-${{ env.TF_ENV }}" > "plan-${{ env.TF_ENV }}.txt"

      - name: Comment Plan on PR (${{ env.TF_ENV }})
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "terraform plan (${{ env.TF_ENV }})"
          path: "plan-${{ env.TF_ENV }}.txt"
