name: terraform-apply
on:
  push:
    branches: [ "main" ]
    paths:
      - "infra/**"

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  GOOGLE_PROJECT: <your_project_id>
  GOOGLE_REGION: europe-west1

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod  # keep if you want approval
    steps:
      - uses: actions/checkout@v4

      # Key-based auth (same secret)
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - uses: hashicorp/setup-terraform@v3
      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Select/Create Workspace (prod)
        run: |
          terraform -chdir=infra workspace select prod \
          || terraform -chdir=infra workspace new prod

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve -input=false -var "project_id=${{ env.GOOGLE_PROJECT }}" -var "region=${{ env.GOOGLE_REGION }}"
